# Numpy

- linear algebra library
- fast


## Vectors
- 1-D ARRAYS

## MATRICES

- 2-D ARRAYS

#### CREATING NUMPY ARRAY

In [1]:
import numpy as np

#create using list
l1 = [1,2,3]

arr = np.array(l1)
print(arr)

[1 2 3]


In [2]:
type(arr)

numpy.ndarray

In [3]:
#ndarray - n -dimensional array

In [4]:
#create 2-d array
l2 = [[1,2,3],[4,5,6],[7,8,9]]

arr2 = np.array(l2)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#double brackets denote 2d , triple denotes 3-d

### ndim
- check dimension of array

In [6]:
arr2.ndim

2

### shape

- returns shape of an array
- returns generally row*column

In [7]:
arr2.shape

(3, 3)

### size

- returns number of elements in array

In [8]:
arr2.size

9

### dtype

- gives datatype of each element

In [10]:
arr2.dtype

dtype('int32')

## DIFFERENT METHODS FOR CREATING BUILTIN ARRAY

## arange

- works exactly like range function
- (start,stop,step)

In [13]:
#create array
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## zeros

- create an array of zeroes
- zero are in float by default

In [14]:
#1d
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
#2d
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#integer zeroes
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## ones

- create an array of ones

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace

- returns evenly spaced numbers between an interval
- (start,stop,number of elements)


In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## FULL

- used to fill any value
- create an array of that same value

In [20]:
np.full((5,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

## Identity

- diagonals are 1 and all other elements 0
- np.eye(number,k)
- k denotes the diagonal
  where 0 is main diagonal
  positive is upper
  negative is lower

In [21]:
#using main diagonal
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# using upper diagonal
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [23]:
#using lower diagonal
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

## RANDOM

- creates an array of random numbers

### rand

- gives uniformly distributed elements bwtween 0 to 1


In [24]:
#1d
np.random.rand(5)

array([0.37100242, 0.29941984, 0.55945379, 0.05005308, 0.70424875])

In [26]:
#2d
np.random.rand(5,5)

array([[0.52336706, 0.75195761, 0.82490315, 0.77450401, 0.9787875 ],
       [0.32272684, 0.34450714, 0.95673441, 0.00570564, 0.10165369],
       [0.04313652, 0.44898333, 0.8927584 , 0.292     , 0.69580398],
       [0.00482908, 0.76870768, 0.54667623, 0.14784115, 0.39845782],
       [0.376934  , 0.9593755 , 0.71755855, 0.45687916, 0.64620068]])

### randn

- gives elements according to normal\gaussian distrubution
- elements are centered around zero

In [27]:
#1d
np.random.randn(5)

array([ 1.56689308, -1.0177676 , -0.1143966 , -1.33031485, -0.28108013])

In [28]:
#2d
np.random.randn(5,5)

array([[ 0.74806108,  0.21674403,  0.73101215,  0.81408634,  0.59990806],
       [-0.16480232, -0.69173193, -0.08873573, -1.12040408, -1.44496465],
       [-1.12073568,  0.69044674, -0.3432656 ,  1.63792439,  0.16720699],
       [ 1.39144274,  0.07128081,  1.62754626,  0.12424332,  0.11796175],
       [-1.02304278,  2.18301278,  0.89894717, -0.34210323,  0.39622702]])

### randint

- returns a number between a certain interval
- low value is inclusive, high value is exclusive
- (low,high,number of elements required), by default number of elements = 1

In [31]:
#single number
np.random.randint(1,100)

40

In [32]:
#10 numbers
np.random.randint(1,100,10)

array([ 1, 28,  5, 78,  7, 84, 47, 78, 87, 77])

## Different numpy methods

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr

array([18, 41,  4, 15, 37, 24, 21, 49, 24, 37])

## Reshape

- returns an array with same elements but new shape
- number of elements should match

In [36]:
#arr to 2d
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr

array([18, 41,  4, 15, 37, 24, 21, 49, 24, 37])

In [38]:
#max value
ranarr.max()

49

In [39]:
#minimum value
ranarr.min()

4

In [40]:
#index of max value
ranarr.argmax()

7

In [41]:
#index of minimum value
ranarr.argmin()

2

## from function

- custom values based on function

In [42]:
np.fromfunction(lambda x,y:x*y,(5,5),dtype=int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

# NUMPY OPERATIONS

## Array with array

In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#addition of element by element basis
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#subtraction
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#multiply
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
#divide
arr//arr

C:\Users\siddh\AppData\Local\Temp\ipykernel_22968\77360758.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## ARRAY WITH SCALAR

- scalar is broadcasted with every element inside array and perform operation
- process is also called broadcasting

In [8]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [10]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

 ## Universal array functions

In [12]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
#exponent
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [14]:
#max
np.max(arr)

10

In [16]:
#sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

## matrix multiplication

- rows in first array should be equal to columns in second

In [17]:
m1 = [[1,2,3],[4,5,6]]
m2 = [[1,1,1],[2,2,2]]

In [18]:
np.dot(m1,m2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [19]:
m1 = [[1,2,3],[4,5,6]]
m2 = [[1,1],[2,2],[3,3]]

In [20]:
np.dot(m1,m2)

array([[14, 14],
       [32, 32]])

## comparison

- returns array of true false

In [23]:
a1 = np.array([5,6,7,8])
a2 = np.array([1,2,3,4])

In [24]:
a1>a2

array([ True,  True,  True,  True])

## select

- used to get array based on condition
- syntax --> np.select(condition_list , choice_list ,)

In [25]:
x = np.arange(10)

In [26]:
condlist = [x<3,x>5]
choice = [x,x**3]

In [27]:
np.select(condlist,choice)

array([  0,   1,   2,   0,   0,   0, 216, 343, 512, 729])

In [28]:
marks = np.array([88,91,67,78,45,30,57])

condlist = [marks>=90,marks>=80,marks>=70,marks>=60,marks<60]
choice = ['A+','A','B','C','F']

In [29]:
np.select(condlist,choice)

array(['A', 'A+', 'C', 'B', 'F', 'F', 'F'], dtype='<U3')

## NUMPY ARRAY INDEXING

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#1d - indexing and slicing are done same as list

In [6]:
arr[7]

7

In [7]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#Broadcast values to 100 till 5th index
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
#Broadcasting cannot be done in the list


### INDEXING 2-D ARRAY OR MATRIX

In [13]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [14]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Double bracket format

- syntax --> array[row][column]

In [16]:
#grab 5

arr_2d[0][0]

5

In [17]:
#grab 1st row
arr_2d[0]

array([ 5, 10, 15])

### BRACKET FORMAT

- syntax = arr[row,column]

In [22]:
#grab element 40
arr_2d[2][1]

40

In [23]:
#slicing
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
#grab bottom two rows
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

### Conditional selection

In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [28]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [29]:
#even numbers
arr[arr%2==0]

array([ 0,  2,  4,  6,  8, 10])