## Fancy Indexing

In [1]:
import numpy as np

a = np.random.randint(1,100,24).reshape(6,4)
a

array([[85,  1, 14, 84],
       [42, 85, 16, 43],
       [17,  7, 67, 37],
       [ 1, 70, 65,  9],
       [ 3, 10,  7, 58],
       [49, 32,  3, 11]])

In [2]:
# Get 1st,3rd and 4th row
a[[0,2,3]]

array([[85,  1, 14, 84],
       [17,  7, 67, 37],
       [ 1, 70, 65,  9]])

In [3]:
# Get all rows and 1st , 3rd and 4th column
a[:,[0,2,3]]

array([[85, 14, 84],
       [42, 16, 43],
       [17, 67, 37],
       [ 1, 65,  9],
       [ 3,  7, 58],
       [49,  3, 11]])

## Boolean Indexing

In [4]:
a

array([[85,  1, 14, 84],
       [42, 85, 16, 43],
       [17,  7, 67, 37],
       [ 1, 70, 65,  9],
       [ 3, 10,  7, 58],
       [49, 32,  3, 11]])

In [5]:
# All numbers greater than 50
a[a > 50]

array([85, 84, 85, 67, 70, 65, 58])

In [8]:
# All numbers greater than 50 and are even
a[(a>50) & (a%2==0)]

array([84, 70, 58])

In [9]:
# All numbers divisible by 7
a[a%7==0]

array([14, 84, 42,  7, 70,  7, 49])

### Broadcasting

In [10]:
# same shape


In [ ]:
# sigmoid
